// Generated by CoffeeScript 1.10.0
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.Engine = (function() {
    function Engine(gl) {
      this.gl = gl;
      this.tick = bind(this.tick, this);
      this.models = [];
      this.startTime = null;
    }

    Engine.prototype.addModel = function(model) {
      return this.models.push(model);
    };

    Engine.prototype.tick = function() {
      var elapsed, i, len, model, ref;
      elapsed = Date.now() - this.startTime;
      this.gl.clear(this.gl.COLOR_BUFFER_BIT | this.gl.DEPTH_BUFFER_BIT);
      ref = this.models;
      for (i = 0, len = ref.length; i < len; i++) {
        model = ref[i];
        model.animate(elapsed);
        model.draw();
      }
      return requestAnimationFrame(this.tick);
    };

    Engine.prototype.start = function() {
      this.startTime = Date.now();
      return this.tick();
    };

    return Engine;

  })();

}).call(this);

//# sourceMappingURL=engine.js.map
