// Generated by CoffeeScript 1.6.3
(function() {
  var Matrix, main;

  main = function() {
    var canvas, gl, m, n, program;
    canvas = document.getElementById('gl');
    gl = canvas.getContext('experimental-webgl');
    program = new ShaderProgram(gl);
    program.addShader(gl.VERTEX_SHADER, 'attribute vec4 a_Position;\nuniform mat4 u_xformMatrix;\nvoid main() {\n     gl_Position = u_xformMatrix * a_Position;\n}');
    program.addShader(gl.FRAGMENT_SHADER, 'void main() {\n  gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);\n}');
    program.activate();
    gl.clearColor(0.0, 0.0, 0.0, 1.0);
    gl.clear(gl.COLOR_BUFFER_BIT);
    m = Matrix.identity().rotate(45, 0, 0, 1).translate(0.5, 0.75, 0).scale(0.5, 0.5, 0.5).array();
    program.setUniformMatrix('u_xformMatrix', m);
    n = program.setAttribPointer('a_Position', [0.0, 0.5, -0.5, -0.5, 0.5, -0.5]);
    return gl.drawArrays(gl.TRIANGLES, 0, n);
  };

  Matrix = (function() {
    function Matrix(array) {
      this.m = array != null ? array : [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1];
    }

    Matrix.identity = function() {
      return new Matrix(null);
    };

    Matrix.rotation = function(angle, x, y, z) {
      var cosB, radian, sinB;
      radian = Math.PI * angle / 180.0;
      cosB = Math.cos(radian);
      sinB = Math.sin(radian);
      return new Matrix([cosB + x * x * (1 - cosB), x * y * (1 - cosB) - z * sinB, x * z * (1 - cosB) + y * sinB, 0.0, y * x * (1 - cosB) + z * sinB, cosB + y * y * (1 - cosB), y * z * (1 - cosB) - x * sinB, 0.0, z * x * (1 - cosB) - y * sinB, z * y * (1 - cosB) + x * sinB, cosB + z * z * (1 - cosB), 0.0, 0.0, 0.0, 0.0, 1.0]);
    };

    Matrix.translation = function(x, y, z) {
      return new Matrix([1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, x, y, z, 1.0]);
    };

    Matrix.scalation = function(x, y, z) {
      return new Matrix([x, 0.0, 0.0, 0.0, 0.0, y, 0.0, 0.0, 0.0, 0.0, z, 0.0, 0.0, 0.0, 0.0, 1.0]);
    };

    Matrix.prototype.rotate = function(angle, x, y, z) {
      var r;
      r = Matrix.rotation(angle, x, y, z);
      return this.multiply(r);
    };

    Matrix.prototype.translate = function(x, y, z) {
      var t;
      t = Matrix.translation(x, y, z);
      return this.multiply(t);
    };

    Matrix.prototype.scale = function(x, y, z) {
      var s;
      s = Matrix.scalation(x, y, z);
      return this.multiply(s);
    };

    Matrix.prototype.multiply = function(b) {
      var i, j, k, mn, n, sum, _i, _j, _k;
      n = b.m;
      mn = [];
      for (i = _i = 0; _i <= 3; i = ++_i) {
        for (j = _j = 0; _j <= 3; j = ++_j) {
          sum = 0;
          for (k = _k = 0; _k <= 3; k = ++_k) {
            sum += this.m[4 * i + k] * n[4 * k + j];
          }
          mn[i * 4 + j] = sum;
        }
      }
      return new Matrix(mn);
    };

    Matrix.prototype.array = function() {
      return new Float32Array(this.m);
    };

    return Matrix;

  })();

  $(main);

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
