// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var canvas, gl, m, n, program;
    canvas = document.getElementById('gl');
    gl = canvas.getContext('experimental-webgl');
    program = new ShaderProgram(gl);
    program.addShader(gl.VERTEX_SHADER, 'attribute vec4 a_Position;\nuniform mat4 u_ModelMatrix;\nvoid main() {\n     gl_Position = u_ModelMatrix * a_Position;\n}');
    program.addShader(gl.FRAGMENT_SHADER, 'void main() {\n  gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);\n}');
    program.activate();
    m = Matrix.identity().rotate(60, 0, 0, 1).translate(0.5, 0.0, 0).array();
    program.setUniformMatrix('u_ModelMatrix', m);
    n = program.setAttribPointer('a_Position', [0.0, 0.3, -0.3, -0.3, 0.3, -0.3]);
    gl.clearColor(0.0, 0.0, 0.0, 1.0);
    gl.clear(gl.COLOR_BUFFER_BIT);
    return gl.drawArrays(gl.TRIANGLES, 0, n);
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
