// Generated by CoffeeScript 1.6.3
(function() {
  this.Matrix = (function() {
    function Matrix(array) {
      this.m = array != null ? array : Matrix.identity().m;
    }

    Matrix.identity = function() {
      return new Matrix([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]);
    };

    Matrix.rotation = function(angle, x, y, z) {
      var cosB, radian, sinB;
      radian = Math.PI * angle / 180.0;
      cosB = Math.cos(radian);
      sinB = Math.sin(radian);
      return new Matrix([cosB + x * x * (1 - cosB), y * x * (1 - cosB) + z * sinB, z * x * (1 - cosB) - y * sinB, 0.0, x * y * (1 - cosB) - z * sinB, cosB + y * y * (1 - cosB), z * y * (1 - cosB) + x * sinB, 0.0, x * z * (1 - cosB) + y * sinB, y * z * (1 - cosB) - x * sinB, cosB + z * z * (1 - cosB), 0.0, 0.0, 0.0, 0.0, 1.0]);
    };

    Matrix.translation = function(x, y, z) {
      return new Matrix([1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, x, y, z, 1.0]);
    };

    Matrix.scalation = function(x, y, z) {
      return new Matrix([x, 0.0, 0.0, 0.0, 0.0, y, 0.0, 0.0, 0.0, 0.0, z, 0.0, 0.0, 0.0, 0.0, 1.0]);
    };

    Matrix.prototype.rotate = function(angle, x, y, z) {
      return Matrix.rotation(angle, x, y, z).multiply(this);
    };

    Matrix.prototype.translate = function(x, y, z) {
      return Matrix.translation(x, y, z).multiply(this);
    };

    Matrix.prototype.scale = function(x, y, z) {
      return Matrix.scalation(x, y, z).multiply(this);
    };

    Matrix.prototype.multiply = function(b) {
      var i, j, k, mn, sum, _i, _j, _k;
      mn = [];
      for (i = _i = 0; _i <= 3; i = ++_i) {
        for (j = _j = 0; _j <= 3; j = ++_j) {
          sum = 0;
          for (k = _k = 0; _k <= 3; k = ++_k) {
            sum += this.m[4 * i + k] * b.m[4 * k + j];
          }
          mn[i * 4 + j] = sum;
        }
      }
      return new Matrix(mn);
    };

    Matrix.prototype.array = function() {
      return new Float32Array(this.m);
    };

    return Matrix;

  })();

}).call(this);

/*
//@ sourceMappingURL=matrix.map
*/
